### ISSUE TITLE
Provide a reusable github action

### ISSUE THREAD

**Issue by leodido** [leodido/rn2md#9]
It would be great to provide a reusable github action; imagine it being used like:

```
uses: actions/rn2md
with:
  token: ...
  repo:
  milestone:
  output: path.txt
```

_Originally posted by @FedeDP in https://github.com/leodido/rn2md/issues/8#issuecomment-1721035699_
